import * as THREE from 'three';
import { subscribeCollisionPlanner } from './collisionAwarePlanner.js';

const MAIN_SCENE_BACKGROUND = 0xeef2f5;
const LIVE_CHECK_INTERVAL_MS = 120;
const NEAR_CLEARANCE_M = 0.08;
const SAMPLE_BUDGET_PER_MESH = 64;
const ROOM_X_LIMIT = 5.8;
const ROOM_Z_LIMIT = 3.8;
const DRAG_SPEED = 0.0045;

const DRAGGABLE_BY_NAME = {
  or_iv_pole: { id: 'iv-pole', label: 'IV pole' },
  or_mayo_stand: { id: 'mayo-stand', label: 'Mayo stand' },
  or_instrument_trolley: { id: 'instrument-trolley', label: 'Instrument trolley' },
  or_anesthesia_workstation: { id: 'anesthesia', label: 'Anesthesia workstation' },
  or_carm_monitor_cart: { id: 'monitor-cart', label: 'C-arm monitor cart' },
  or_surgeon: { id: 'surgeon', label: 'Surgeon' },
  or_scrub_nurse: { id: 'scrub-nurse', label: 'Scrub nurse' },
};

const state = { scene:null,camera:null,renderer:null,equipmentGroup:null,safetyGroup:null,cArmRoot:null,ready:false,editMode:false,selectedId:null,selectedLabel:null,layoutDirty:false,layoutRevision:0,liveCollisionStatus:'SEARCHING',liveCollisionLabel:null,liveMinClearanceM:null,message:null,subscribers:new Set() };
let installed=false, originalRender=null, pointerDom=null, selectionHelper=null, selectedRoot=null, dragState=null, initialLayout=null;
const raycaster=new THREE.Raycaster(), pointer=new THREE.Vector2();
const snapshot=()=>({ready:state.ready,editMode:state.editMode,selectedId:state.selectedId,selectedLabel:state.selectedLabel,layoutDirty:state.layoutDirty,layoutRevision:state.layoutRevision,liveCollisionStatus:state.liveCollisionStatus,liveCollisionLabel:state.liveCollisionLabel,liveMinClearanceM:state.liveMinClearanceM,message:state.message});
const emit=()=>{const next=snapshot();state.subscribers.forEach(fn=>{try{fn(next)}catch(e){console.warn('[OR interaction] subscriber failed',e)}})};
export const getOperatingRoomInteractionSnapshot=()=>snapshot();
export const subscribeOperatingRoomInteraction=listener=>{state.subscribers.add(listener);listener(snapshot());return()=>state.subscribers.delete(listener)};
const isMainSimulatorScene=scene=>scene?.background?.isColor&&scene.background.getHex()===MAIN_SCENE_BACKGROUND;
const safetyObjectForId=(id,edge=false)=>state.safetyGroup?.getObjectByName(edge?`safety_edges_${id}`:`safety_${id}`)||null;
const saveLayout=()=>{if(!state.equipmentGroup||!state.safetyGroup)return null;const equipment={};Object.entries(DRAGGABLE_BY_NAME).forEach(([name,info])=>{const root=state.equipmentGroup.getObjectByName(name);if(!root)return;equipment[info.id]={objectName:name,position:root.position.clone(),quaternion:root.quaternion.clone(),scale:root.scale.clone(),bubblePosition:safetyObjectForId(info.id)?.position.clone()||null,edgePosition:safetyObjectForId(info.id,true)?.position.clone()||null}});return equipment};
const findDraggableRoot=object=>{let cursor=object;while(cursor&&cursor!==state.equipmentGroup){if(DRAGGABLE_BY_NAME[cursor.name])return cursor;cursor=cursor.parent}return null};
const selectedInfo=root=>root?DRAGGABLE_BY_NAME[root.name]||null:null;
const updateSelectionHelper=()=>{if(!state.scene)return;if(selectionHelper?.parent)selectionHelper.parent.remove(selectionHelper);selectionHelper=null;if(!selectedRoot||!state.editMode)return;selectionHelper=new THREE.BoxHelper(selectedRoot,0xffd166);selectionHelper.name='or_layout_selection_helper';selectionHelper.renderOrder=2000;state.scene.add(selectionHelper)};
const selectRoot=root=>{selectedRoot=root||null;const info=selectedInfo(root);state.selectedId=info?.id||null;state.selectedLabel=info?.label||null;updateSelectionHelper();emit()};
export const setOperatingRoomEditMode=enabled=>{state.editMode=Boolean(enabled);if(!state.editMode){dragState=null;selectRoot(null)}else{state.message='EDIT OR: hold LEFT or RIGHT mouse on equipment and drag. Camera is locked during edit.';emit()}};
export const toggleOperatingRoomEditMode=()=>setOperatingRoomEditMode(!state.editMode);
const markLayoutDirty=label=>{state.layoutDirty=true;state.layoutRevision+=1;state.message=`${label||'OR object'} moved. Run PREVIEW PATH again before MOVE C-ARM.`};
const moveSafetyEnvelope=(id,dx,dz)=>{const bubble=safetyObjectForId(id),edges=safetyObjectForId(id,true);if(bubble){bubble.position.x+=dx;bubble.position.z+=dz;bubble.updateMatrixWorld(true)}if(edges){edges.position.x+=dx;edges.position.z+=dz;edges.updateMatrixWorld(true)}};
const pointerToNdc=event=>{const rect=pointerDom?.getBoundingClientRect();if(!rect?.width||!rect?.height)return false;pointer.x=((event.clientX-rect.left)/rect.width)*2-1;pointer.y=-((event.clientY-rect.top)/rect.height)*2+1;return true};
const consume=event=>{event.preventDefault();event.stopPropagation();if(typeof event.stopImmediatePropagation==='function')event.stopImmediatePropagation()};
const cameraBasis=()=>{const forward=new THREE.Vector3();state.camera.getWorldDirection(forward);forward.y=0;if(forward.lengthSq()<1e-6)forward.set(0,0,-1);forward.normalize();const right=new THREE.Vector3().crossVectors(forward,new THREE.Vector3(0,1,0)).normalize();return{forward,right}};
const onPointerDown=event=>{if(!state.editMode||!state.ready||!state.equipmentGroup||!(event.button===0||event.button===2))return;consume(event);if(!pointerToNdc(event))return;raycaster.setFromCamera(pointer,state.camera);const hits=raycaster.intersectObject(state.equipmentGroup,true);const root=hits.map(h=>findDraggableRoot(h.object)).find(Boolean)||null;if(!root){selectRoot(null);state.message='EDIT OR active: click/hold directly on an IV pole, stand, cart, surgeon, or nurse.';emit();return}selectRoot(root);const info=selectedInfo(root);dragState={pointerId:event.pointerId,root,info,lastX:event.clientX,lastY:event.clientY,moved:false};state.message=`Dragging ${info.label} with ${event.button===2?'RIGHT':'LEFT'} mouse.`;emit();try{pointerDom.setPointerCapture(event.pointerId)}catch{}};
const onPointerMove=event=>{if(!dragState||event.pointerId!==dragState.pointerId||!state.editMode)return;consume(event);const dxPx=event.clientX-dragState.lastX,dyPx=event.clientY-dragState.lastY;dragState.lastX=event.clientX;dragState.lastY=event.clientY;if(Math.abs(dxPx)+Math.abs(dyPx)<0.1)return;const{forward,right}=cameraBasis();const worldDelta=right.multiplyScalar(dxPx*DRAG_SPEED).add(forward.multiplyScalar(-dyPx*DRAG_SPEED));const parent=dragState.root.parent;const p0=parent.worldToLocal(new THREE.Vector3(0,0,0));const p1=parent.worldToLocal(worldDelta.clone());const localDelta=p1.sub(p0);const oldX=dragState.root.position.x,oldZ=dragState.root.position.z;dragState.root.position.x=THREE.MathUtils.clamp(oldX+localDelta.x,-ROOM_X_LIMIT,ROOM_X_LIMIT);dragState.root.position.z=THREE.MathUtils.clamp(oldZ+localDelta.z,-ROOM_Z_LIMIT,ROOM_Z_LIMIT);const actualDx=dragState.root.position.x-oldX,actualDz=dragState.root.position.z-oldZ;if(Math.abs(actualDx)+Math.abs(actualDz)<1e-8)return;dragState.root.updateMatrixWorld(true);moveSafetyEnvelope(dragState.info.id,actualDx,actualDz);dragState.moved=true;if(selectionHelper)selectionHelper.update()};
const finishDrag=event=>{if(!dragState||event.pointerId!==dragState.pointerId)return;consume(event);const done=dragState;dragState=null;try{pointerDom.releasePointerCapture(event.pointerId)}catch{}if(done.moved){markLayoutDirty(done.info.label);emit()}};
const blockContextMenu=event=>{if(state.editMode){event.preventDefault();event.stopPropagation()}};
const attachPointerDom=dom=>{if(!dom||pointerDom===dom)return;if(pointerDom){pointerDom.removeEventListener('pointerdown',onPointerDown,true);pointerDom.removeEventListener('pointermove',onPointerMove,true);pointerDom.removeEventListener('pointerup',finishDrag,true);pointerDom.removeEventListener('pointercancel',finishDrag,true);pointerDom.removeEventListener('contextmenu',blockContextMenu,true)}pointerDom=dom;pointerDom.style.touchAction='none';pointerDom.addEventListener('pointerdown',onPointerDown,true);pointerDom.addEventListener('pointermove',onPointerMove,true);pointerDom.addEventListener('pointerup',finishDrag,true);pointerDom.addEventListener('pointercancel',finishDrag,true);pointerDom.addEventListener('contextmenu',blockContextMenu,true)};
const captureRuntime=(scene,camera,renderer)=>{if(!isMainSimulatorScene(scene))return;state.scene=scene;state.camera=camera;state.renderer=renderer;state.equipmentGroup=scene.getObjectByName('operating_room_equipment_layer');state.safetyGroup=scene.getObjectByName('operating_room_safety_bubbles');attachPointerDom(renderer?.domElement);const wasReady=state.ready;state.ready=Boolean(state.equipmentGroup&&state.safetyGroup&&state.camera&&state.renderer);if(state.ready&&!initialLayout)initialLayout=saveLayout();if(state.ready!==wasReady)emit()};
export const resetOperatingRoomLayout=()=>{if(!initialLayout||!state.equipmentGroup)return false;Object.entries(initialLayout).forEach(([id,saved])=>{const root=state.equipmentGroup.getObjectByName(saved.objectName);if(root){root.position.copy(saved.position);root.quaternion.copy(saved.quaternion);root.scale.copy(saved.scale);root.updateMatrixWorld(true)}const bubble=safetyObjectForId(id);if(bubble&&saved.bubblePosition)bubble.position.copy(saved.bubblePosition);const edges=safetyObjectForId(id,true);if(edges&&saved.edgePosition)edges.position.copy(saved.edgePosition)});state.safetyGroup?.updateMatrixWorld(true);if(selectionHelper)selectionHelper.update();state.layoutDirty=true;state.layoutRevision+=1;state.message='OR layout reset. Run PREVIEW PATH again before MOVE C-ARM.';emit();return true};
const findCArmRoot=scene=>{let best=null,bestScore=-Infinity;scene?.children?.forEach(child=>{if(!child?.isGroup||child.userData?.operatingRoomEnvironment||child.userData?.operatingRoomSafety)return;let meshCount=0,torusCount=0,cylinderCount=0;child.traverse(object=>{if(!object.isMesh)return;meshCount++;if(object.geometry?.type==='TorusGeometry')torusCount++;if(object.geometry?.type==='CylinderGeometry')cylinderCount++});if(torusCount<2||meshCount<8)return;const score=torusCount*30+cylinderCount*2+meshCount;if(score>bestScore){best=child;bestScore=score}});return best};
const safetyEntries=()=>{if(!state.safetyGroup)return[];state.safetyGroup.updateMatrixWorld(true);return state.safetyGroup.children.filter(child=>child?.isMesh&&child.name?.startsWith('safety_')&&!child.name?.startsWith('safety_edges_')).map(mesh=>({id:mesh.name.slice('safety_'.length),box:new THREE.Box3().setFromObject(mesh)}))};
const sampleMeshWorldPoints=(mesh,out)=>{const attr=mesh.geometry?.attributes?.position;if(!attr?.count)return;const step=Math.max(1,Math.ceil(attr.count/SAMPLE_BUDGET_PER_MESH)),point=new THREE.Vector3();for(let i=0;i<attr.count;i+=step){point.fromBufferAttribute(attr,i).applyMatrix4(mesh.matrixWorld);out.push(point.clone())}};
const liveCollisionCheck=()=>{if(!state.ready||!state.scene)return;state.scene.updateMatrixWorld(true);if(!state.cArmRoot||state.cArmRoot.parent!==state.scene)state.cArmRoot=findCArmRoot(state.scene);if(!state.cArmRoot)return;const points=[];state.cArmRoot.traverse(o=>{if(o.isMesh&&o.visible!==false)sampleMeshWorldPoints(o,points)});const entries=safetyEntries();let collisionId=null,closestId=null,minClearance=Infinity;for(const obstacle of entries){let obstacleMin=Infinity;for(const point of points){if(obstacle.box.containsPoint(point)){obstacleMin=0;collisionId=obstacle.id;break}obstacleMin=Math.min(obstacleMin,obstacle.box.distanceToPoint(point))}if(obstacleMin<minClearance){minClearance=obstacleMin;closestId=obstacle.id}if(collisionId)break}const labelForId=id=>Object.values(DRAGGABLE_BY_NAME).find(i=>i.id===id)?.label||(id==='patient-table'?'Patient / operating table':id==='surgical-light'?'Surgical light':id?.replaceAll('-',' '));const nextStatus=collisionId?'COLLISION':minClearance<=NEAR_CLEARANCE_M?'NEAR':'CLEAR',nextLabel=labelForId(collisionId||closestId)||null,nextClearance=Number.isFinite(minClearance)?minClearance:null,changed=nextStatus!==state.liveCollisionStatus||nextLabel!==state.liveCollisionLabel||Math.abs((nextClearance??0)-(state.liveMinClearanceM??0))>0.005;state.liveCollisionStatus=nextStatus;state.liveCollisionLabel=nextLabel;state.liveMinClearanceM=collisionId?0:nextClearance;if(changed)emit()};
const installRendererCapture=()=>{if(originalRender)return;originalRender=THREE.WebGLRenderer.prototype.render;THREE.WebGLRenderer.prototype.render=function(scene,camera){captureRuntime(scene,camera,this);return originalRender.call(this,scene,camera)}};
const installKeyboard=()=>window.addEventListener('keydown',event=>{const tag=(event.target?.tagName||'').toLowerCase();if(['input','textarea','select'].includes(tag)||event.repeat)return;if(event.key.toLowerCase()==='e')toggleOperatingRoomEditMode();if(event.key==='Escape'&&state.editMode)setOperatingRoomEditMode(false)});
const installMoveGuard=()=>document.addEventListener('click',event=>{const button=event.target?.closest?.('button');if(!button||!state.layoutDirty)return;const text=(button.textContent||'').trim().toUpperCase();if(!text.includes('MOVE C-ARM'))return;event.preventDefault();event.stopPropagation();state.message='OR layout changed. Run PREVIEW PATH again before MOVE C-ARM.';emit()},true);
const installPlannerSync=()=>subscribeCollisionPlanner(planner=>{if(!state.layoutDirty||!['DIRECT_CLEAR','DIRECT_NEAR','REROUTED','BLOCKED'].includes(planner.status))return;state.layoutDirty=false;state.message=planner.status==='BLOCKED'?'New OR layout checked: no safe route is currently available.':'New OR layout checked. MOVE C-ARM may use the latest previewed route.';emit()});
export const installOperatingRoomInteraction=()=>{if(installed||typeof window==='undefined')return;installed=true;installRendererCapture();installKeyboard();installMoveGuard();installPlannerSync();window.setInterval(liveCollisionCheck,LIVE_CHECK_INTERVAL_MS)};
installOperatingRoomInteraction();
